# Generated by Django 4.2.1 on 2023-05-29 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=255, verbose_name='Отчество')),
                ('years', models.DateField(verbose_name='Годы жизни')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фотография личности')),
                ('bio', models.TextField(blank=True, verbose_name='Текст публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название публикации')),
                ('content', models.TextField(verbose_name='Текст публикации')),
                ('theme', models.CharField(choices=[('Статья', 'Статья'), ('Факт', 'Факт'), ('Юмор', 'Юмор')], default=('Событие', 'Событие'), max_length=255, verbose_name='Тема публикации')),
                ('category', models.CharField(choices=[('Статья', 'Статья'), ('Факт', 'Факт'), ('Юмор', 'Юмор')], default=('Статья', 'Статья'), max_length=255, verbose_name='Категория публикации')),
                ('year_start', models.DateField(verbose_name='Дата начала события или первого появления вещи')),
                ('year_end', models.DateField(verbose_name='Дата окончания события')),
                ('time_publish', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото события или вещи')),
                ('is_published', models.BooleanField(default=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Publication', to='core.person', verbose_name='Связанные личности')),
            ],
        ),
    ]
