# Generated by Django 4.2.1 on 2023-05-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='years',
        ),
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='person',
            name='deathday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата смерти'),
        ),
    ]
