# Generated by Django 4.2.1 on 2023-05-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categories_themes_alter_publication_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='time_publish',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='person',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
