# Generated by Django 4.2.1 on 2023-05-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_person_time_publish_person_time_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.FileField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фотография личности'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='photo',
            field=models.FileField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото события или вещи'),
        ),
    ]
