# Generated by Django 4.2.1 on 2023-05-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_person_photo_alter_publication_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='person',
        ),
        migrations.AddField(
            model_name='publication',
            name='person',
            field=models.ManyToManyField(related_name='Publication', to='core.person', verbose_name='Связанные личности'),
        ),
    ]
