# Generated by Django 4.2.1 on 2023-06-01 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_person_photo_alter_publication_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['surname']},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['time_publish']},
        ),
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication', to='core.categories', verbose_name='Категория публикации'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='person',
            field=models.ManyToManyField(related_name='publication', to='core.person', verbose_name='Связанные личности'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication', to='core.themes', verbose_name='Тема публикации'),
        ),
    ]
