# Generated by Django 4.2.1 on 2023-06-03 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_alter_person_options_alter_publication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категории публикаций'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['surname'], 'verbose_name': 'Историческая личность'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-time_publish'], 'verbose_name': 'Публикация'},
        ),
        migrations.AlterModelOptions(
            name='themes',
            options={'verbose_name': 'Темы публикаций'},
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, verbose_name='Никнейм профиля')),
                ('status', models.TextField(blank=True, verbose_name='Статус профиля')),
                ('photo', models.ImageField(blank=True, upload_to='photos/profile/%Y/%m/%d/', verbose_name='Фото профиля')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
            },
        ),
    ]
