# Generated by Django 4.2.1 on 2023-06-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_profile_photo_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='person',
            field=models.ManyToManyField(blank=True, related_name='publication', to='core.person', verbose_name='Связанные личности'),
        ),
    ]
