# Generated by Django 4.2.1 on 2023-06-04 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_publication_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='core.profile', verbose_name='Автор публикации'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='core.categories', verbose_name='Категория публикации'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='person',
            field=models.ManyToManyField(blank=True, related_name='persons', to='core.person', verbose_name='Связанные личности'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='core.themes', verbose_name='Тема публикации'),
        ),
    ]
