# Generated by Django 4.2.1 on 2023-06-04 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_publication_author_alter_publication_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_profiles', to='core.profile', verbose_name='Автор личности'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication_profiles', to='core.profile', verbose_name='Автор публикации'),
        ),
    ]
