# Generated by Django 4.2.1 on 2023-06-04 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='publication_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
    ]
